### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by dpmcsuss** [jovo/PyGraphStat#1]
I think we should try to stick with numpy, scipy, etc naming conventions.
Notably:
- modules (aka filenames) should be lower_case 
- class names should be CamelCase
- methods should be lower_case

Thoughts?

**Comment by jovo** [comment]
sounds like a great plan.  i doubt i conformed to it.  you can fix my errors, or i can fix them, both are fine. let's close this issue once we've corrected everything.
